DROP SCHEMA IF EXISTS users CASCADE;
CREATE SCHEMA users;

DROP TABLE IF EXISTS users.user;
CREATE TABLE users.user (
	user_id INT not null generated by default as identity,
	"name" varchar(100) default null,
	username varchar(50) default null,
	hpassword varchar(256) default null,
	email varchar(100) default null,
	CONSTRAINT pk_user PRIMARY KEY (user_id)
);